import { NextResponse } from 'next/server';
import { supabaseAdmin, isSupabaseConfigured } from '@/lib/supabase';
import { INITIAL_LISTINGS, RS_CITIES } from '@/lib/data';

export async function GET() {
  if (!isSupabaseConfigured()) {
    return NextResponse.json({ error: 'Supabase is not configured' }, { status: 503 });
  }
  
  try {
    const { count, error: countError } = await (supabaseAdmin
      .from('listings') as any)
      .select('*', { count: 'exact', head: true });
    
    if (countError) {
      console.error('Supabase error checking listings count:', JSON.stringify(countError, null, 2));
      // If table doesn't exist, we should report it clearly
      if (countError.code === '42P01') {
        return NextResponse.json({ 
          error: 'Table "listings" does not exist. Please create it in Supabase SQL Editor.',
          details: countError.message,
          sql: `
CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  price DECIMAL NOT NULL,
  price_kg DECIMAL NOT NULL,
  avg_weight DECIMAL NOT NULL,
  quantity INTEGER NOT NULL,
  location TEXT NOT NULL,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  seller TEXT NOT NULL,
  seller_rating DECIMAL DEFAULT 5.0,
  verified BOOLEAN DEFAULT FALSE,
  verification_requested BOOLEAN DEFAULT FALSE,
  sold BOOLEAN DEFAULT FALSE,
  image TEXT,
  description TEXT,
  images JSONB DEFAULT '[]'::JSONB,
  videos JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read access on listings" ON listings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to create listings" ON listings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow public update on listings" ON listings FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on listings" ON listings FOR DELETE USING (true);
          `
        }, { status: 500 });
      }
      return NextResponse.json({ error: 'Failed to check listings count', details: countError.message || JSON.stringify(countError) }, { status: 500 });
    }

  // Create default admin user
  const adminEmail = 'adriano.prog@gmail.com';
  const { data: existingAdmin, error: adminCheckError } = await (supabaseAdmin
    .from('users') as any)
    .select('id, is_admin')
    .eq('email', adminEmail)
    .maybeSingle();

    if (adminCheckError) {
      console.error('Supabase error checking admin user:', JSON.stringify(adminCheckError, null, 2));
      if (adminCheckError.code === '42P01') {
        return NextResponse.json({ 
          error: 'Table "users" does not exist. Please create it in Supabase SQL Editor.',
          details: adminCheckError.message,
          sql: `
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  city TEXT,
  password TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
          `
        }, { status: 500 });
      }
    }

  if (!existingAdmin) {
    const { error: insertAdminError } = await (supabaseAdmin
      .from('users') as any)
      .insert([
        {
          name: 'Administrador',
          email: adminEmail,
          phone: '51999999999',
          city: 'Porto Alegre',
          password: 'admin', // In a real app, use a secure password and hash it
          is_admin: true
        }
      ]);
    
    if (insertAdminError) {
      console.error('Supabase error creating admin user:', JSON.stringify(insertAdminError, null, 2));
    } else {
      console.log('Admin user created successfully');
    }
  } else if (!existingAdmin.is_admin) {
    // If user exists but is not admin, promote them
    const { error: updateAdminError } = await (supabaseAdmin
      .from('users') as any)
      .update({ is_admin: true })
      .eq('email', adminEmail);
    
    if (updateAdminError) {
      console.error('Supabase error promoting user to admin:', JSON.stringify(updateAdminError, null, 2));
    } else {
      console.log('User promoted to admin successfully');
    }
  }

  if (count === 0 && (INITIAL_LISTINGS as any[]).length > 0) {
    const formattedListings = (INITIAL_LISTINGS as any[]).map(l => {
      const city = RS_CITIES.find(c => l.location.includes(c.name.toUpperCase())) || RS_CITIES[0];
      return {
        title: l.title,
        price: l.price,
        price_kg: l.priceKg,
        avg_weight: l.avgWeight,
        quantity: l.quantity,
        category: l.category,
        seller: l.seller,
        seller_rating: l.sellerRating,
        verified: !!l.verified,
        image: l.image,
        images: l.images,
        description: l.description,
        location: l.location || 'RS',
        lat: city.lat,
        lng: city.lng
      };
    });

    const { error: insertError } = await (supabaseAdmin
      .from('listings') as any)
      .insert(formattedListings);

    if (insertError) {
      console.error('Supabase error seeding database:', JSON.stringify(insertError, null, 2));
      return NextResponse.json({ error: 'Failed to seed database', details: insertError.message || JSON.stringify(insertError) }, { status: 500 });
    }

    return NextResponse.json({ message: 'Database seeded successfully with admin user' });
  }

    return NextResponse.json({ message: 'Admin user checked/created. Database already has listings.' });
  } catch (error: any) {
    console.error('Unexpected error in seed route:', error.message || error);
    return NextResponse.json({ error: 'Unexpected error in seed route', details: error.message }, { status: 500 });
  }
}
