-- Create messages table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  sender_name TEXT NOT NULL,
  sender_email TEXT NOT NULL,
  sender_phone TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Policies for messages
CREATE POLICY "Allow public insert on messages" ON messages
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read their own messages" ON messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM listings
      WHERE listings.id = messages.listing_id
      AND (
        listings.seller = (SELECT name FROM users WHERE email = auth.jwt() ->> 'email')
        OR
        (SELECT is_admin FROM users WHERE email = auth.jwt() ->> 'email') = true
      )
    )
  );

CREATE POLICY "Allow public update on messages" ON messages
  FOR UPDATE USING (true);

CREATE POLICY "Allow public delete on messages" ON messages
  FOR DELETE USING (true);
