-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  city TEXT,
  password TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create listings table
CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  price DECIMAL NOT NULL,
  price_kg DECIMAL NOT NULL,
  avg_weight DECIMAL NOT NULL,
  quantity INTEGER NOT NULL,
  location TEXT NOT NULL,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  seller TEXT NOT NULL,
  seller_rating DECIMAL DEFAULT 5.0,
  verified BOOLEAN DEFAULT FALSE,
  image TEXT,
  description TEXT,
  images JSONB DEFAULT '[]'::JSONB,
  videos JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create favorites table
CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_email, listing_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

-- Policies for listings
CREATE POLICY "Allow public read access on listings" ON listings
  FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users to create listings" ON listings
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Policies for users
CREATE POLICY "Allow public read access on users" ON users
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert on users" ON users
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow users to update their own data" ON users
  FOR UPDATE USING (true); -- In a real app, restrict this to the user themselves

CREATE POLICY "Allow public delete on users" ON users
  FOR DELETE USING (true); -- In a real app, restrict this to admins
