-- ==============================================================================
-- PADRONIZAÇÃO DE CATEGORIAS DE ANIMAIS - GADO GAÚCHO
-- ==============================================================================

-- 1. Criar tabela de categorias oficiais
CREATE TABLE IF NOT EXISTS public.animal_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- Popular categorias oficiais (Boi substitui Boi Castrado, Touro adicionado)
INSERT INTO public.animal_categories (name) VALUES
  ('Boi'), 
  ('Gado de Leite'), 
  ('Novilha'), 
  ('Novilho'),
  ('Terneira'), 
  ('Terneiro'), 
  ('Touro'), 
  ('Vaca'), 
  ('Vaca com Cria'), 
  ('Vaca Prenha')
ON CONFLICT (name) DO NOTHING;

-- 2. Criar tabela de aliases/sinônimos para normalização
CREATE TABLE IF NOT EXISTS public.animal_category_aliases (
  alias TEXT PRIMARY KEY,
  category_id INT NOT NULL REFERENCES public.animal_categories(id) ON DELETE CASCADE
);

-- Popular mapeamentos/sinônimos (Boi mapeia boi castrado, bois, boi; Touro mapeia touro)
INSERT INTO public.animal_category_aliases (alias, category_id) VALUES
  ('boi', (SELECT id FROM public.animal_categories WHERE name = 'Boi')),
  ('bois', (SELECT id FROM public.animal_categories WHERE name = 'Boi')),
  ('boi castrado', (SELECT id FROM public.animal_categories WHERE name = 'Boi')),
  ('touro', (SELECT id FROM public.animal_categories WHERE name = 'Touro')),
  ('novilha', (SELECT id FROM public.animal_categories WHERE name = 'Novilha')),
  ('novilhas', (SELECT id FROM public.animal_categories WHERE name = 'Novilha')),
  ('novilho', (SELECT id FROM public.animal_categories WHERE name = 'Novilho')),
  ('novilhos', (SELECT id FROM public.animal_categories WHERE name = 'Novilho')),
  ('terneira', (SELECT id FROM public.animal_categories WHERE name = 'Terneira')),
  ('terneiras', (SELECT id FROM public.animal_categories WHERE name = 'Terneira')),
  ('terneiro', (SELECT id FROM public.animal_categories WHERE name = 'Terneiro')),
  ('terneiros', (SELECT id FROM public.animal_categories WHERE name = 'Terneiro')),
  ('vaca', (SELECT id FROM public.animal_categories WHERE name = 'Vaca')),
  ('vacas', (SELECT id FROM public.animal_categories WHERE name = 'Vaca')),
  ('vaca gorda', (SELECT id FROM public.animal_categories WHERE name = 'Vaca')),
  ('vaca descarte', (SELECT id FROM public.animal_categories WHERE name = 'Vaca')),
  ('vaca prenha', (SELECT id FROM public.animal_categories WHERE name = 'Vaca Prenha')),
  ('vacas prenhes', (SELECT id FROM public.animal_categories WHERE name = 'Vaca Prenha')),
  ('vaca com cria', (SELECT id FROM public.animal_categories WHERE name = 'Vaca com Cria')),
  ('vacas com cria', (SELECT id FROM public.animal_categories WHERE name = 'Vaca com Cria'))
ON CONFLICT (alias) DO NOTHING;

-- 3. Adicionar a coluna de relacionamento nas tabelas principais
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS category_id INT REFERENCES public.animal_categories(id) ON DELETE SET NULL;
ALTER TABLE public.auction_offers ADD COLUMN IF NOT EXISTS category_id INT REFERENCES public.animal_categories(id) ON DELETE SET NULL;

-- 4. Função de Normalização de Categoria Automática
CREATE OR REPLACE FUNCTION public.fn_normalize_animal_category()
RETURNS TRIGGER AS $$
DECLARE
  v_category_id INT;
  v_standard_name TEXT;
  v_input_category TEXT := TRIM(NEW.category);
BEGIN
  -- Se foi passado category_id diretamente, atualiza o texto da category correspondente
  IF NEW.category_id IS NOT NULL THEN
    SELECT name INTO v_standard_name
    FROM public.animal_categories
    WHERE id = NEW.category_id;
    
    IF v_standard_name IS NOT NULL THEN
      NEW.category := v_standard_name;
      RETURN NEW;
    END IF;
  END IF;

  -- Senão, tenta normalizar com base na string category
  IF v_input_category IS NOT NULL AND v_input_category <> '' THEN
    -- Tentar encontrar pelo alias (case-insensitive)
    SELECT aca.category_id, ac.name INTO v_category_id, v_standard_name
    FROM public.animal_category_aliases aca
    JOIN public.animal_categories ac ON aca.category_id = ac.id
    WHERE LOWER(aca.alias) = LOWER(v_input_category);

    -- Se não encontrar pelo alias, tentar pelo nome padrão diretamente (case-insensitive)
    IF v_category_id IS NULL THEN
      SELECT id, name INTO v_category_id, v_standard_name
      FROM public.animal_categories
      WHERE LOWER(name) = LOWER(v_input_category);
    END IF;

    -- Definir os valores normalizados
    IF v_category_id IS NOT NULL THEN
      NEW.category_id := v_category_id;
      NEW.category := v_standard_name;
    ELSE
      NEW.category_id := NULL;
    END IF;
  ELSE
    NEW.category_id := NULL;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Triggers para listings e auction_offers
DROP TRIGGER IF EXISTS trg_normalize_listings_category ON public.listings;
CREATE TRIGGER trg_normalize_listings_category
BEFORE INSERT OR UPDATE ON public.listings
FOR EACH ROW
EXECUTE FUNCTION public.fn_normalize_animal_category();

DROP TRIGGER IF EXISTS trg_normalize_offers_category ON public.auction_offers;
CREATE TRIGGER trg_normalize_offers_category
BEFORE INSERT OR UPDATE ON public.auction_offers
FOR EACH ROW
EXECUTE FUNCTION public.fn_normalize_animal_category();

-- 6. Migração inicial dos dados existentes para a nova chave estrangeira category_id e normalização do texto
--listings
UPDATE public.listings l
SET category = COALESCE(
  (SELECT ac.name FROM public.animal_category_aliases aca JOIN public.animal_categories ac ON aca.category_id = ac.id WHERE LOWER(TRIM(aca.alias)) = LOWER(TRIM(l.category))),
  (SELECT name FROM public.animal_categories WHERE LOWER(TRIM(name)) = LOWER(TRIM(l.category))),
  l.category
);

UPDATE public.listings l
SET category_id = (SELECT id FROM public.animal_categories WHERE name = l.category);

--auction_offers
UPDATE public.auction_offers ao
SET category = COALESCE(
  (SELECT ac.name FROM public.animal_category_aliases aca JOIN public.animal_categories ac ON aca.category_id = ac.id WHERE LOWER(TRIM(aca.alias)) = LOWER(TRIM(ao.category))),
  (SELECT name FROM public.animal_categories WHERE LOWER(TRIM(name)) = LOWER(TRIM(ao.category))),
  ao.category
);

UPDATE public.auction_offers ao
SET category_id = (SELECT id FROM public.animal_categories WHERE name = ao.category);
