-- ==============================================================================
-- CRIAÇÃO DA TABELA DE ALERTAS DE OPORTUNIDADES (DEMANDAS DE COMPRADORES)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.opportunity_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  category_id INT REFERENCES public.animal_categories(id) ON DELETE CASCADE,
  min_price NUMERIC,
  max_price NUMERIC,
  min_weight NUMERIC,
  max_weight NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.opportunity_alerts ENABLE ROW LEVEL SECURITY;

-- 1. Qualquer pessoa (visitante ou logado) pode criar um alerta
CREATE POLICY "opportunity_alerts_insert_policy" ON public.opportunity_alerts
  FOR INSERT WITH CHECK (true);

-- 2. Leitura: O próprio usuário que criou (se logado) ou administradores
CREATE POLICY "opportunity_alerts_select_policy" ON public.opportunity_alerts
  FOR SELECT USING (
    (user_id IS NOT NULL AND auth.uid()::text = user_id) OR
    (SELECT is_admin FROM public.users WHERE id = auth.uid()::text) = true
  );

-- 3. Deleção: O próprio usuário que criou ou administradores
CREATE POLICY "opportunity_alerts_delete_policy" ON public.opportunity_alerts
  FOR DELETE USING (
    (user_id IS NOT NULL AND auth.uid()::text = user_id) OR
    (SELECT is_admin FROM public.users WHERE id = auth.uid()::text) = true
  );
