-- ==============================================================================
-- CRIAÇÃO DA TABELA DE LOGS DO SISTEMA (Para depuração em ambientes serverless)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL DEFAULT 'info', -- 'info', 'warn', 'error'
  context TEXT,                       -- ex: 'api/opportunity-alerts'
  message TEXT NOT NULL,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;

-- 1. Apenas administradores podem visualizar os logs
CREATE POLICY "system_logs_select_policy" ON public.system_logs
  FOR SELECT USING (
    (SELECT is_admin FROM public.users WHERE id = auth.uid()::text) = true
  );

-- 2. Qualquer inserção é permitida para que o backend possa registrar erros mesmo se estiver usando a anonKey
CREATE POLICY "system_logs_insert_policy" ON public.system_logs
  FOR INSERT WITH CHECK (true);
